[package]
name = "unroxy-net"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1", default-features = false, features = ["io-util"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies.tokio]
version = "1"
features = ["net"]

[target.'cfg(target_family = "wasm")'.dependencies.tokio]
version = "1"
features = ["rt", "time"]

[target.'cfg(target_family = "wasm")'.dependencies]
wasip2 = "1"
