[package]
name = "unroxy"
version.workspace = true
edition.workspace = true

[[bin]]
name = "unroxy"
path = "src/main.rs"

[dependencies]
unroxy-psiphon = { path = "../psiphon" }
unroxy-proxy = { path = "../proxy" }
anyhow = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
libc = { workspace = true }
lru = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"
tracing-subscriber = "0.3"
wreq = { workspace = true }
wreq-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
